# Generated by Django 2.1.7 on 2019-04-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastes',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('user', models.TextField(default='anonymous')),
                ('paste', models.TextField()),
            ],
        ),
    ]
