# Generated by Django 2.1.7 on 2019-04-26 07:20

from django.db import migrations, models
from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=True)),
                ('title', models.TextField()),
                ('user', models.TextField(default='anonymous')),
                ('paste', JSONField()),
                ('token', models.TextField()),
            ],
        ),
    ]
