# Generated by Django 2.2.1 on 2019-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pastes',
            name='token',
            field=models.TextField(default='null'),
        ),
    ]
